from __future__ import annotations

from dataclasses import dataclass

SHEET_HEADERS: dict[str, tuple[str, ...]] = {
    "WorkbookMeta": ("key", "value", "updated_at"),
    "Skus": (
        "sku_id",
        "description",
        "unit",
        "detector_class",
        "reference_image_path",
        "active",
        "created_at",
        "updated_at",
    ),
    "Locations": (
        "location_id",
        "description",
        "location_type",
        "active",
        "created_at",
        "updated_at",
    ),
    "Inventory": (
        "inventory_id",
        "location_id",
        "sku_id",
        "quantity",
        "unit",
        "version",
        "updated_at",
        "last_event_id",
    ),
    "Tasks": (
        "task_id",
        "order_id",
        "sku_id",
        "expected_quantity",
        "unit",
        "source_location_id",
        "destination_location_id",
        "status",
        "selected",
        "created_at",
        "updated_at",
        "completed_event_id",
    ),
    "SourceProfiles": (
        "source_profile_id",
        "name",
        "source_type",
        "file_path",
        "camera_index",
        "network_url_redacted",
        "analysis_fps",
        "preview_fps",
        "requested_width",
        "requested_height",
        "reconnect_enabled",
        "active",
        "created_at",
        "updated_at",
    ),
    "ZoneProfiles": (
        "zone_profile_id",
        "source_profile_id",
        "name",
        "version",
        "source_width",
        "source_height",
        "shelf_polygon_json",
        "interaction_polygon_json",
        "exit_polygon_json",
        "counting_line_json",
        "shelf_side_sign",
        "uncertainty_band_norm",
        "crossing_confirm_frames",
        "quiet_seconds",
        "stable_seconds",
        "hard_idle_seconds",
        "merge_window_seconds",
        "active",
        "created_at",
        "updated_at",
    ),
    "Sessions": (
        "session_id",
        "source_profile_id",
        "zone_profile_id",
        "task_id",
        "sku_id",
        "location_id",
        "status",
        "started_at",
        "ended_at",
        "captured_frames",
        "analyzed_frames",
        "dropped_frames",
        "late_results",
        "mean_latency_ms",
        "p95_latency_ms",
        "error_code",
    ),
    "Events": (
        "event_id",
        "session_id",
        "task_id",
        "zone_profile_id",
        "zone_version",
        "state",
        "observed_sku_id",
        "observed_quantity",
        "observed_unit",
        "observed_source_location_id",
        "final_sku_id",
        "final_quantity",
        "final_unit",
        "final_source_location_id",
        "aggregate_confidence",
        "integrity_flags_json",
        "review_reason",
        "decision",
        "started_at",
        "ended_at",
        "evidence_path",
        "created_at",
        "decided_at",
        "applied_at",
        "mutation_id",
    ),
    "EventActions": (
        "action_id",
        "event_id",
        "action_sequence",
        "track_id",
        "transition_index",
        "action_type",
        "delta",
        "source_timestamp_ms",
        "frame_sequence",
        "confidence",
        "bbox_json",
        "created_at",
    ),
    "Reviews": (
        "review_id",
        "event_id",
        "decision",
        "operator_id",
        "original_values_json",
        "final_values_json",
        "reason",
        "created_at",
    ),
    "AuditLog": (
        "audit_id",
        "timestamp",
        "operator_id",
        "action",
        "entity_type",
        "entity_id",
        "request_id",
        "before_json",
        "after_json",
        "result",
        "error_code",
        "details_json",
    ),
    "MutationReceipts": (
        "mutation_id",
        "idempotency_key",
        "event_id",
        "mutation_hash",
        "committed_at",
        "workbook_version_before",
        "workbook_version_after",
        "result_json",
    ),
}

PRIMARY_KEYS = {
    "WorkbookMeta": "key",
    "Skus": "sku_id",
    "Locations": "location_id",
    "Inventory": "inventory_id",
    "Tasks": "task_id",
    "SourceProfiles": "source_profile_id",
    "ZoneProfiles": "zone_profile_id",
    "Sessions": "session_id",
    "Events": "event_id",
    "EventActions": "action_id",
    "Reviews": "review_id",
    "AuditLog": "audit_id",
    "MutationReceipts": "mutation_id",
}

REQUIRED_METADATA_KEYS = frozenset(
    {
        "schema_version",
        "workbook_id",
        "scenario_id",
        "created_at",
        "last_committed_at",
        "last_mutation_id",
    }
)


@dataclass(frozen=True, slots=True)
class ValidationReport:
    errors: tuple[str, ...] = ()

    @property
    def valid(self) -> bool:
        return not self.errors


class WorkbookFailure(Exception):
    def __init__(self, code: str, detail: str) -> None:
        super().__init__(f"{code}: {detail}")
        self.code = code
        self.detail = detail

